Repository depromeet/bodymood-backend, pull requests merged in 2021-11, with the labels that each got.

#41 refactor: Logger 편하게 사용하도록 수정
  dgdg-api/src/main/java/com/depromeet/dgdg/config/redis/EmbeddedRedisConfig.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/controller/advice/ControllerExceptionAdvice.kt
  dgdg-common/src/main/java/com/depromeet/dgdg/common/utils/LoggerUtils.kt
  dgdg-domain/src/main/java/com/depromeet/dgdg/domain/domain/exercise/ExerciseCategory.kt
Labels: enhancement

#42 fix: 가끔씩 테스트가 깨지는 문제
  dgdg-api/src/main/resources/application.yml
Labels: bug

#44 fix: 잘못된 이메일 포맷, 파일 확장자, 허용하지 않는 카테고리 depth인 경우 커스텀하게 에러 메시지를 보내주도록 수정
  dgdg-common/src/main/java/com/depromeet/dgdg/common/ErrorCode.java
  dgdg-common/src/main/java/com/depromeet/dgdg/common/utils/FileUtils.kt
  dgdg-domain/src/main/java/com/depromeet/dgdg/domain/domain/exercise/ExerciseCategory.kt
  dgdg-domain/src/main/java/com/depromeet/dgdg/domain/domain/user/Email.java
Labels: enhancement

#45 fix: 인터셉터에서 토큰에서 가져온 payload에 해당하는 유저가 존재하는지 확인하는 로직 추가
  dgdg-api/src/main/java/com/depromeet/dgdg/config/auth/AuthInterceptor.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/auth/dto/request/AuthRequest.kt
Labels: enhancement

#46 refactor: 포스터 API 추가 요청사항 추가 및 수정
  dgdg-api/src/main/java/com/depromeet/dgdg/controller/advice/ControllerExceptionAdvice.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/controller/poster/PosterController.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/poster/PosterService.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/poster/dto/PosterPhotoResponse.kt
  dgdg-domain/src/main/java/com/depromeet/dgdg/domain/domain/poster/Emotion.kt
  dgdg-domain/src/main/java/com/depromeet/dgdg/domain/domain/poster/Poster.kt
  dgdg-domain/src/main/java/com/depromeet/dgdg/domain/domain/poster/repository/PosterRepositoryCustom.kt
  dgdg-domain/src/main/java/com/depromeet/dgdg/domain/domain/poster/repository/PosterRepositoryCustomImpl.kt
Labels: enhancement

#47 feat: 포스터 관련 커스텀 에러 메시지 설정
  dgdg-api/src/main/java/com/depromeet/dgdg/controller/advice/ControllerExceptionAdvice.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/controller/poster/PosterController.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/controller/poster/dto/PosterRequest.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/poster/PosterService.kt
  dgdg-api/src/main/resources/logback-spring.xml
  dgdg-common/src/main/java/com/depromeet/dgdg/common/ErrorCode.java
Labels: enhancement

#48 feat: 프레임워크 필터에서 Forwarded Header를 넘겨주도록 설정
  dgdg-api/build.gradle
  dgdg-api/src/main/resources/application.yml
Labels: enhancement

#53 feat: 운영환경 S3 버킷 설정
  build.gradle
  dgdg-api/build.gradle
  dgdg-api/src/main/resources/application-aws.yml
  dgdg-api/src/main/resources/application-cache.yml
  dgdg-api/src/main/resources/application-s3.yml
Labels: enhancement

#57 feat: .http 추가
  dgdg-api/http/auth.http
  dgdg-api/http/category.http
  dgdg-api/http/main.http
  dgdg-api/http/poster.http
  dgdg-api/http/temp/image.jpeg
  dgdg-api/http/user.http
  http-client.env.json
Labels: enhancement

#51 feature: 회원 탈퇴 구현
  dgdg-api/http/user.http
  dgdg-api/src/main/java/com/depromeet/dgdg/controller/LocalTestController.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/controller/user/UserController.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/auth/AppleLoginService.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/auth/AuthService.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/auth/KakaoLoginService.java
  dgdg-api/src/main/java/com/depromeet/dgdg/service/poster/PosterService.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/user/UserService.kt
  dgdg-common/src/main/java/com/depromeet/dgdg/common/ErrorCode.java
  dgdg-domain/src/main/java/com/depromeet/dgdg/domain/domain/user/User.java
  dgdg-domain/src/main/java/com/depromeet/dgdg/domain/domain/user/UserStatus.kt
  dgdg-domain/src/main/java/com/depromeet/dgdg/domain/domain/user/repository/UserRepository.java
  dgdg-domain/src/main/java/com/depromeet/dgdg/domain/domain/user/repository/UserRepositoryCustom.java
  dgdg-domain/src/main/java/com/depromeet/dgdg/domain/domain/user/repository/UserRepositoryCustomImpl.java
  dgdg-domain/src/main/resources/db/migration/V2__add_user_status.sql
Labels: enhancement

#59 v1.0.1
  VERSION
  dgdg-api/http/user.http
  dgdg-api/src/main/java/com/depromeet/dgdg/controller/LocalTestController.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/controller/user/UserController.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/auth/AppleLoginService.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/auth/AuthService.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/auth/KakaoLoginService.java
  dgdg-api/src/main/java/com/depromeet/dgdg/service/poster/PosterService.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/user/UserService.kt
  dgdg-common/src/main/java/com/depromeet/dgdg/common/ErrorCode.java
  dgdg-domain/src/main/java/com/depromeet/dgdg/domain/domain/user/User.java
  dgdg-domain/src/main/java/com/depromeet/dgdg/domain/domain/user/UserStatus.kt
  dgdg-domain/src/main/java/com/depromeet/dgdg/domain/domain/user/repository/UserRepository.java
  dgdg-domain/src/main/java/com/depromeet/dgdg/domain/domain/user/repository/UserRepositoryCustom.java
  dgdg-domain/src/main/java/com/depromeet/dgdg/domain/domain/user/repository/UserRepositoryCustomImpl.java
  dgdg-domain/src/main/resources/db/migration/V2__add_user_status.sql
  dgdg-domain/src/main/resources/db/migration/V3__update_user_index.sql
Labels: enhancement

#61 fix: M1에서 임베디드 레디스 호환성 문제 해결하기 위해서 로컬에서는 캐시를 사용하지 않도록 하는 방안
  build.gradle
  dgdg-api/build.gradle
  dgdg-api/src/main/java/com/depromeet/dgdg/config/cache/CacheConfig.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/config/redis/EmbeddedRedisConfig.kt
Labels: bug

#62 fix: throws 테스트 assertj에서 kotest로 변경해서 테스트 진행
  README.md
  build.gradle
  dgdg-api/src/test/java/com/depromeet/dgdg/provider/token/JwtAuthTokenProviderTest.kt
  dgdg-api/src/test/java/com/depromeet/dgdg/service/auth/AuthServiceTest.kt
  dgdg-api/src/test/java/com/depromeet/dgdg/service/user/UserServiceTest.kt
  dgdg-common/src/test/java/com/depromeet/dgdg/common/utils/FileUtilsTest.kt
  dgdg-domain/src/test/java/com/depromeet/dgdg/domain/exercise/ExerciseCategoryTest.kt
Labels: documentation

#64 v1.0.2
  README.md
  build.gradle
  dgdg-api/build.gradle
  dgdg-api/src/main/java/com/depromeet/dgdg/config/auth/AuthInterceptor.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/config/cache/CacheConfig.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/config/redis/EmbeddedRedisConfig.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/controller/LocalTestController.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/controller/emotion/EmotionController.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/mapper/emotion/EmotionMapper.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/provider/token/AuthTokenProvider.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/provider/token/JwtAuthTokenProvider.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/auth/AppleLoginService.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/auth/AuthService.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/auth/KakaoLoginService.java
  dgdg-api/src/test/java/com/depromeet/dgdg/controller/emotion/EmotionControllerTest.kt
  dgdg-api/src/test/java/com/depromeet/dgdg/provider/token/JwtAuthTokenProviderTest.kt
  dgdg-api/src/test/java/com/depromeet/dgdg/service/auth/AuthServiceTest.kt
  dgdg-api/src/test/java/com/depromeet/dgdg/service/user/UserServiceTest.kt
  dgdg-common/build.gradle
  dgdg-common/src/main/java/com/depromeet/dgdg/common/utils/ProcessUtils.kt
  dgdg-common/src/test/java/com/depromeet/dgdg/common/utils/FileUtilsTest.kt
  dgdg-domain/src/main/java/com/depromeet/dgdg/domain/domain/poster/Emotion.kt
  dgdg-domain/src/test/java/com/depromeet/dgdg/domain/exercise/ExerciseCategoryTest.kt
Labels: enhancement
