Repository depromeet/bodymood-backend, pull requests merged in 2021-10, with the labels that each got.

#12 refactor: JWT Token 관련 리팩토링
  dgdg-api/src/main/java/com/depromeet/dgdg/config/auth/AuthInterceptor.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/controller/LocalTestController.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/provider/token/AuthTokenProvider.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/provider/token/JwtAuthTokenProvider.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/provider/token/dto/AuthTokenPayload.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/provider/token/dto/JwtProperties.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/.gitkeep
  dgdg-api/src/main/resources/application-jwt.yml
  dgdg-api/src/test/java/com/depromeet/dgdg/provider/token/JwtAuthTokenProviderTest.kt
Labels: documentation

#13 feat: 커스텀 Exception 정의
  dgdg-common/src/main/java/com/depromeet/dgdg/common/ErrorCode.java
  dgdg-common/src/main/java/com/depromeet/dgdg/common/exception/BadRequestException.kt
  dgdg-common/src/main/java/com/depromeet/dgdg/common/exception/ConflictException.kt
  dgdg-common/src/main/java/com/depromeet/dgdg/common/exception/ForbiddenException.kt
  dgdg-common/src/main/java/com/depromeet/dgdg/common/exception/NotFoundException.kt
  dgdg-common/src/main/java/com/depromeet/dgdg/common/exception/ServiceUnavailableException.kt
  dgdg-common/src/main/java/com/depromeet/dgdg/common/exception/UnAuthorizedException.kt
Labels: enhancement, help wanted

#16 feat : AWS secrets manager 및 PostgreSQL 셋팅
  .github/workflows/common.yaml
  .gitignore
  dgdg-api/build.gradle
  dgdg-api/src/main/java/com/depromeet/dgdg/EncryptionPropertyListener.kt
  dgdg-api/src/main/resources/META-INF/spring.factories
  dgdg-api/src/main/resources/application-aws.yml
  dgdg-api/src/main/resources/application-oauth.yml
  dgdg-api/src/main/resources/application.yml
  dgdg-api/src/test/resources/application.yml
  dgdg-domain/build.gradle
  dgdg-domain/src/main/resources/application-db.yml
Labels: enhancement

#23 feat: 회원정보를 조회 및 수정 API, 토큰 재발급 API, 로그아웃 API
  build.gradle
  dgdg-api/src/main/java/com/depromeet/dgdg/config/auth/AuthResponse.java
  dgdg-api/src/main/java/com/depromeet/dgdg/config/auth/UserIdArgumentResolver.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/controller/LocalTestController.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/controller/advice/ControllerExceptionAdvice.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/controller/auth/AuthController.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/controller/auth/KakaoLoginController.java
  dgdg-api/src/main/java/com/depromeet/dgdg/controller/user/UserController.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/provider/token/AuthTokenProvider.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/provider/token/JwtAuthTokenProvider.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/provider/token/dto/JwtProperties.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/auth/AuthService.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/auth/KakaoLoginService.java
  dgdg-api/src/main/java/com/depromeet/dgdg/service/auth/dto/request/AuthRequest.java
  dgdg-api/src/main/java/com/depromeet/dgdg/service/auth/dto/request/RefreshTokenRequest.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/auth/dto/response/RefreshTokenResponse.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/user/UserService.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/user/dto/request/UserRequest.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/user/dto/response/UserResponse.kt
  dgdg-api/src/main/resources/application-jwt.yml
  dgdg-api/src/test/java/com/depromeet/dgdg/provider/token/JwtAuthTokenProviderTest.kt
  dgdg-api/src/test/java/com/depromeet/dgdg/service/auth/AuthServiceTest.kt
  dgdg-api/src/test/java/com/depromeet/dgdg/service/user/UserServiceTest.kt
  dgdg-domain/src/main/java/com/depromeet/dgdg/domain/domain/user/User.java
  dgdg-domain/src/main/java/com/depromeet/dgdg/domain/domain/user/UserCreator.kt
  dgdg-domain/src/main/java/com/depromeet/dgdg/domain/domain/user/repository/UserRepositoryCustom.java
  dgdg-domain/src/main/java/com/depromeet/dgdg/domain/domain/user/repository/UserRepositoryCustomImpl.java
Labels: enhancement

#25 fix: refresh token 검증 로직 추가
  dgdg-api/src/main/java/com/depromeet/dgdg/controller/advice/ControllerExceptionAdvice.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/provider/token/AuthTokenProvider.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/provider/token/JwtAuthTokenProvider.kt
  dgdg-api/src/main/java/com/depromeet/dgdg/service/auth/AuthService.kt
  dgdg-api/src/test/java/com/depromeet/dgdg/provider/token/JwtAuthTokenProviderTest.kt
  dgdg-api/src/test/java/com/depromeet/dgdg/service/auth/AuthServiceTest.kt
  dgdg-common/src/main/java/com/depromeet/dgdg/common/ErrorCode.java
Labels: enhancement
